name: Update Data Monthly

on:
  schedule:
    # Run on the first day of each month at 2:00 AM UTC
    - cron: '0 2 1 * *'
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-22.04
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run data update script
        run: python scripts/update_all_data.py --verbose
        timeout-minutes: 30

      - name: Check for changes
        id: verify-changes
        run: |
          if git diff --quiet data/; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changed files:"
            git diff --name-only data/
          fi

      - name: Configure git
        if: steps.verify-changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        if: steps.verify-changes.outputs.has_changes == 'true'
        run: |
          git add data/*.json
          git commit -m "chore: update data files - $(date +'%Y-%m-%d %H:%M:%S UTC')"
          git push

      - name: Report status
        if: always()
        run: |
          if [ "${{ steps.verify-changes.outputs.has_changes }}" = "true" ]; then
            echo "Data files updated and pushed successfully"
          else
            echo "No changes detected in data files"
          fi
